spring.application.name=xl-ai-rag
server.port=9006
spring.ai.dashscope.api-key=sk-c31cf*******5687d1da1b

# elasticsearch ????
spring.elasticsearch.uris= https://localhost:9200  # 8.x ???? HTTPS???? https
spring.elasticsearch.username= username 
spring.elasticsearch.password= password
#spring.elasticsearch.ssl.certificate-authorities = # ?? Elasticsearch ? CA ??
#spring.elasticsearch.ssl.verify-hostnames = # ??????????????????????